name: Example Workflow

on:
  push:
    branches: [main]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        env:
          SECRET_VALUE: ${{ secrets.APP_CREDENTIALS }}
