jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      SECRET_VALUE: ${{ secrets.APP_CREDENTIALS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python mainWorkFlowtest.py
