name: workflowexp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  example_job:
    runs-on: windows-latest
    env:
      SECRET_VALUE: ${{ secrets.APP_CREDENTIALS2 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python mainWorkFlowtest.py
